// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM248_-pQmNUQBayVVHNeMSE8Xx9omzPk',
    appId: '1:234960529736:web:5bb5a33a3696c4e8e4ab7d',
    messagingSenderId: '234960529736',
    projectId: 'quis2-39bc8',
    authDomain: 'quis2-39bc8.firebaseapp.com',
    storageBucket: 'quis2-39bc8.firebasestorage.app',
    measurementId: 'G-PLQD45LGEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQP2f8dClkaEDZ4cU8yNhAuLMAkk42gk',
    appId: '1:234960529736:android:1a8444b6cb3f1b53e4ab7d',
    messagingSenderId: '234960529736',
    projectId: 'quis2-39bc8',
    storageBucket: 'quis2-39bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaJSkYCCehkmxJXkfRqCVnryvxnrTDRkM',
    appId: '1:234960529736:ios:f78c9db2b9b31999e4ab7d',
    messagingSenderId: '234960529736',
    projectId: 'quis2-39bc8',
    storageBucket: 'quis2-39bc8.firebasestorage.app',
    iosBundleId: 'com.example.quis2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaJSkYCCehkmxJXkfRqCVnryvxnrTDRkM',
    appId: '1:234960529736:ios:f78c9db2b9b31999e4ab7d',
    messagingSenderId: '234960529736',
    projectId: 'quis2-39bc8',
    storageBucket: 'quis2-39bc8.firebasestorage.app',
    iosBundleId: 'com.example.quis2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM248_-pQmNUQBayVVHNeMSE8Xx9omzPk',
    appId: '1:234960529736:web:516c871fda003da7e4ab7d',
    messagingSenderId: '234960529736',
    projectId: 'quis2-39bc8',
    authDomain: 'quis2-39bc8.firebaseapp.com',
    storageBucket: 'quis2-39bc8.firebasestorage.app',
    measurementId: 'G-BFZ51CTFB4',
  );
}
